trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  
stages:
- stage: QA
  jobs:
  - job: API
    steps:

    - task: UseDotNet@2
      displayName: 'Install .NET Core sdk'
      inputs:
        packageType: sdk
        version: 3.1.102
        installationPath: $(Agent.ToolsDirectory)/dotnet
        
#    - task: SonarCloudPrepare@1
#      displayName: Prepare Sonar Cloud
#      inputs:
#        SonarCloud: 'myhelper'
#        organization: 'pastore'
#        scannerMode: 'MSBuild'
#        projectKey: 'pastore_MyHelper'

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: 'restore'
        feedsToUse: 'select'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'custom'
        custom: 'msbuild'
        arguments: '-property:Configuration=$(buildConfiguration)'

#    - task: SonarCloudAnalyze@1
#      displayName: Run Code Analyzer

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/MyHelper.Tests.Unit/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
  
  - job: ClientApp
    steps:

      - task: NodeTool@0
        displayName: 'Install Node.js'
        inputs:
          versionSpec: '10.15.1'

      - task: Npm@1
        displayName: 'Npm install'
        inputs:
          command: install
          workingDir: 'MyHelper.ClientApp'

      - task: Npm@1
        displayName: 'Set version of the build'
        inputs:
          command: custom
          customCommand: run build-version:patch
          workingDir: 'MyHelper.ClientApp'

      - task: Bash@3
        displayName: 'Push to GitHub'
        inputs:
          targetType: 'inline'
          script: |
            git checkout master
            git commit -m 'Update version of the build [ci skip]'
            echo https://${TOKEN}@github.com/pastore/MyHelper.git
            git push https://${TOKEN}@github.com/pastore/MyHelper.git
        env:
          TOKEN: $(PAT)
      - task: Npm@1
        displayName: 'Build Angular'
        inputs:
          command: custom
          customCommand: run build
          workingDir: 'MyHelper.ClientApp'

      - task: Npm@1
        displayName: 'Test Angular'
        inputs:
          command: custom
          customCommand: run test -- --watch=false
          workingDir: 'MyHelper.ClientApp'

      - task: PublishTestResults@2
        displayName: 'Publish Angular test results'
        condition: succeededOrFailed()
        inputs:
          searchFolder: $(System.DefaultWorkingDirectory)/MyHelper.ClientApp/junit
          testResultsFormat: 'JUnit'
          testResultsFiles: '**/tests.xml'
          testRunTitle: 'Angular'