trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  
stages:
- stage: QA
  jobs:
  - job: API
    steps:

    # Install dotnet sdk
    - task: UseDotNet@2
      displayName: 'Install .NET Core sdk'
      inputs:
        packageType: sdk
        version: 2.1.301
        installationPath: $(Agent.ToolsDirectory)/dotnet

    # Build
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'

    # Test
    - task: DotNetCoreCLI@2
      inputs:
        command: test
        projects: '**/MyHelper.Tests.Unit/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

     # Publish tests 
    - task: PublishTestResults@2
      displayName: Publish tests
      condition: succeededOrFailed()
      inputs:
        testRunner: VSTest
        testResultsFiles: '**/MyHelper.Tests.Unit/results/*.trx'
